project_name: helmfile
builds:
  - id: helmfile
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
      - -X go.szostok.io/version.commit={{.FullCommit}}
      - -X go.szostok.io/version.commitDate={{.CommitDate}}
      - -X go.szostok.io/version.dirtyBuild=false
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
changelog:
  use: github-native
