# Test this locally with:
#   $ docker run --rm -it -v $(pwd):$(pwd) --workdir $(pwd) python:3 bash
#   # pip install -r docs/requirements.txt
#   # mkdocs serve
#   # mkdocs build
#   $ ls -lah site/
site_name: helmfile
site_author: Helmfile Authors

repo_name: helmfile/helmfile/
repo_url: https://github.com/helmfile/helmfile/
edit_uri: ''

docs_dir: docs

nav:
  - Home: index.md
  - Getting Started:
    - Writing Helmfile: writing-helmfile.md
    - Values and Merging: values-and-merging.md
    - Environments: environments.md
    - Releases & DAG: releases.md
  - Configuration:
    - helmfile.yaml Reference: configuration.md
    - Templating: templating.md
    - Template Functions: templating_funcs.md
    - Built-in Objects: builtin-objects.md
    - HCL Functions: hcl_funcs.md
    - Paths Overview: paths.md
  - CLI Reference: cli.md
  - Advanced:
    - Advanced Features: advanced-features.md
    - Hooks: hooks.md
    - Secrets: remote-secrets.md
    - Shared Configuration: shared-configuration-across-teams.md
    - Integrations: integrations.md
  - Experimental Features: experimental-features.md
  - About:
    - Users: users.md
    - License: license.md
    - Contributing: contributing.md

theme:
  name: readthedocs
  features:
    - navigation.tabs
  collapse_navigation: false
  hljs_languages:
    - yaml
    - dockerfile

markdown_extensions:
  # meta, toc, table and fenced_code extensions are included by default
  - extra
  - admonition
  - smarty
  - sane_lists
  - nl2br
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
